services:
  web:
    build: .
    command: sh -c "python3 tree_menu/manage.py makemigrations && python3 tree_menu/manage.py migrate && python3 tree_menu/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"  
    volumes:
      - .:/app
